version: '3'

services:
  traefik:
    image: traefik:v2.6
    container_name: traefik_proxy
    restart: unless-stopped
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - ./config/static.yml:/etc/traefik/traefik.yml:ro
      - ./config/dynamic.yml:/etc/traefik/dynamic.yml:ro
      - ./certs:/etc/certs
    ports:
      - "80:80"
      - "443:443"
    networks:
      - net-traefik

  jaeger:
    image: jaegertracing/all-in-one:1.17
    environment:
      COLLECTOR_ZIPKIN_HTTP_PORT: 9411
    networks:
      - net-traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.jaeger.rule=Host(`jaeger.docker.localhost`)"
      - "traefik.http.services.mailjaegerhog.loadbalancer.server.port=16686"

networks:
  net-traefik:
    driver: bridge